[package]
name = "pixbox"
version = "0.1.0"
edition = "2021"

[lib]
name = "pixbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["rustls-tls", "stream"] }
tokio = { version = "1", features = ["sync", "time", "rt", "macros"] }
futures-util = "0.3"
sha2 = "0.10"
base64 = "0.22"
url = "2"
getrandom = "0.2"
image = "0.25"
chrono = "0.4"
